#!/usr/bin/env python3
"""Tool factory for ~/.ncode/.

Scaffolds deterministic local helpers under ~/.ncode/scripts/. Does NOT
auto-promote into skills/, agents/, or commands/. Output is a starting point
that the agent/user reviews, edits, and only then promotes.

Usage:
  python3 tool_factory.py <name> --summary "..." [--lang py|sh]
  python3 tool_factory.py <name> --summary "..." --dry-run

Produces:
  ~/.ncode/scripts/<name>.<ext>
  ~/.ncode/scripts/<name>.md   (purpose/spec doc)
"""
import argparse
import os
import sys
from pathlib import Path

SCRIPTS_DIR = Path.home() / ".ncode" / "scripts"
SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)


PY_TEMPLATE = '''#!/usr/bin/env python3
"""{summary}

Generated by tool_factory.py. Review before promoting.
"""
import argparse
import json
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description="{summary}")
    parser.add_argument("--dry-run", action="store_true", help="report only, no mutation")
    parser.add_argument("--json", action="store_true", help="emit JSON")
    args = parser.parse_args()

    result = {{"status": "ok", "dry_run": args.dry_run}}
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(result)
    sys.exit(0)


if __name__ == "__main__":
    main()
'''

SH_TEMPLATE = '''#!/usr/bin/env bash
# {summary}
# Generated by tool_factory.py. Review before promoting.
set -euo pipefail

dry_run=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) dry_run=1 ;;
    --help) echo "Usage: $0 [--dry-run]"; exit 0 ;;
  esac
done

echo "status: ok (dry_run=$dry_run)"
'''

DOC_TEMPLATE = '''# {name}

{summary}

## Inputs

- (document expected inputs/flags here)

## Outputs

- (document expected outputs here)

## Validation

- `[ ]` dry-run produces expected report
- `[ ]` mutation path verified on a test fixture
- `[ ]` rollback procedure documented

## Promotion gate

Promote to skills/ only after:
1. dry-run + live run both produce expected output
2. docs above are filled in
3. orphan/drift not flagged by `validate_harness.py`
'''


def main():
    parser = argparse.ArgumentParser(description="Scaffold a local helper")
    parser.add_argument("name", help="helper name")
    parser.add_argument("--summary", required=True, help="one-line purpose")
    parser.add_argument("--lang", choices=["py", "sh"], default="py")
    parser.add_argument("--dry-run", action="store_true", help="show plan without writing")
    args = parser.parse_args()

    name = args.name.replace("-", "_") if args.lang == "py" else args.name
    ext = args.lang
    script_path = SCRIPTS_DIR / f"{name}.{ext}"
    doc_path = SCRIPTS_DIR / f"{name}.md"

    if script_path.exists() and not args.dry_run:
        print(f"ERR: {script_path} already exists", file=sys.stderr)
        sys.exit(1)

    plan = [
        f"script: {script_path}",
        f"doc:    {doc_path}",
        f"lang:   {args.lang}",
        f"summary: {args.summary}",
    ]
    if args.dry_run:
        print("dry-run plan:")
        for p in plan:
            print(f"  {p}")
        return

    if ext == "py":
        content = PY_TEMPLATE.format(summary=args.summary)
        script_path.write_text(content, encoding="utf-8")
        os.chmod(script_path, 0o755)
    else:
        content = SH_TEMPLATE.format(summary=args.summary)
        script_path.write_text(content, encoding="utf-8")
        os.chmod(script_path, 0o755)

    doc_path.write_text(DOC_TEMPLATE.format(name=name, summary=args.summary), encoding="utf-8")
    print(f"scaffolded:\n  {script_path}\n  {doc_path}")
    print("\nreview, edit, then run: python3 ~/.ncode/scripts/validate_harness.py")


if __name__ == "__main__":
    main()