#!/usr/bin/env python3
"""Scaffold, behaviorally validate, and version local helpers.

Validation requires an implemented .contract.json and executes its cases.
Legacy scaffold syntax remains supported.
"""
import argparse
import json
import os
import re
import shutil
import tempfile
from datetime import datetime, timezone
from tool_contracts import validate, bundle_files
from sips_runtime.events import atomic_write_json
from sips_runtime.canonical import canonical_hash
import sys
from pathlib import Path

from sips_paths import harness_home, harness_scripts_dir, plugin_root

SCRIPTS_DIR = harness_scripts_dir()
SOURCE_SCRIPTS_DIR = plugin_root() / "scripts"
SKILLS_DIR = harness_home() / "skills"
SUBCOMMANDS = {"scaffold", "validate", "promote"}


PY_TEMPLATE = '''#!/usr/bin/env python3
"""Generated by tool_factory.py. Implement before promoting."""
import argparse
import json
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description={summary!r})
    parser.add_argument("--dry-run", action="store_true", help="report only, no mutation")
    parser.add_argument("--json", action="store_true", help="emit JSON")
    args = parser.parse_args()

    result = {{"status": "not_implemented", "dry_run": args.dry_run}}
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(result)
    sys.exit(2)


if __name__ == "__main__":
    main()
'''

SH_TEMPLATE = '''#!/usr/bin/env bash
# {summary}
# Generated by tool_factory.py. Review before promoting.
set -euo pipefail

dry_run=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) dry_run=1 ;;
    --help) echo "Usage: $0 [--dry-run]"; exit 0 ;;
  esac
done

echo "status: not_implemented (dry_run=$dry_run)"
exit 2
'''

DOC_TEMPLATE = '''# {name}

{summary}

## Inputs

- (document expected inputs/flags here)

## Outputs

- (document expected outputs here)

## Validation

- `[ ]` dry-run produces expected report
- `[ ]` mutation path verified on a test fixture
- `[ ]` rollback procedure documented

## Promotion gate

Promote to skills/ only after:
1. dry-run + live run both produce expected output
2. docs above are filled in
3. orphan/drift not flagged by `validate_harness.py`
'''

def _resolve_paths(name: str, lang: str):
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]*", name):
        raise ValueError("helper name must be a simple identifier")
    sanitized = name.replace("-", "_") if lang == "py" else name
    ext = lang
    return sanitized, SCRIPTS_DIR / f"{sanitized}.{ext}", SCRIPTS_DIR / f"{sanitized}.md"


def cmd_scaffold(args):
    name, script_path, doc_path = _resolve_paths(args.name, args.lang)

    if script_path.exists() and not args.dry_run:
        print(f"ERR: {script_path} already exists", file=sys.stderr)
        sys.exit(1)

    plan = [
        f"script: {script_path}",
        f"doc:    {doc_path}",
        f"contract: {script_path.with_suffix('.contract.json')}",
        f"lang:   {args.lang}",
        f"summary: {args.summary}",
    ]
    if args.dry_run:
        print("dry-run plan:")
        for p in plan:
            print(f"  {p}")
        return

    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    template = PY_TEMPLATE if args.lang == "py" else SH_TEMPLATE
    script_path.write_text(template.format(summary=args.summary if args.lang == "py" else " ".join(args.summary.splitlines())), encoding="utf-8")
    os.chmod(script_path, 0o755)
    doc_path.write_text(DOC_TEMPLATE.format(name=name, summary=args.summary), encoding="utf-8")
    atomic_write_json(script_path.with_suffix('.contract.json'), {
        'schema': 'sips.tool-contract.v1', 'status': 'draft', 'version': '1',
        'description': args.summary, 'inputs': [], 'outputs': [], 'preconditions': [],
        'effects': [], 'failure_semantics': '', 'resources': [], 'cases': []})
    print(f"scaffolded:\n  {script_path}\n  {doc_path}")
    print("\nreview, edit, then run: python3 ${SIPS_HOME:-$HOME/.codex/sips}/scripts/tool_factory.py validate " + name)


def cmd_validate(args):
    name, script, _ = _resolve_paths(args.name, args.lang)
    if getattr(args, "script", None):
        script = Path(args.script).expanduser().resolve()
        if script.suffix != "." + args.lang:
            raise ValueError("script language does not match --lang")
    elif not script.exists():
        script = SOURCE_SCRIPTS_DIR / script.name
    from sips_runtime.adaptation import AdaptationController
    receipt, receipt_path = AdaptationController().validate_tool(script)
    receipt['receipt_path'] = str(receipt_path)
    print(json.dumps(receipt, indent=2))
    if not receipt['ready_for_promote']:
        raise SystemExit(1)
    return receipt, script


def cmd_promote(args):
    receipt, script = cmd_validate(args)
    name = script.stem
    from sips_runtime.adaptation import AdaptationController
    skill_dir = SKILLS_DIR / name
    destination = AdaptationController().promote_tool(script, receipt, skill_dir)
    entry = destination / script.name
    print(json.dumps({'ok': True, 'promoted_to': str(destination), 'script': str(entry),
                      'skill_md': str(skill_dir / 'SKILL.md'),
                      'host_discovery': 'unverified'}, indent=2))


def _rewrite_legacy_argv(argv):
    """If argv[0] is not a known subcommand, prepend 'scaffold'."""
    if not argv:
        return argv
    first = argv[0]
    if first in SUBCOMMANDS or first.startswith("-"):
        return argv
    return ["scaffold"] + argv


def main():
    argv = _rewrite_legacy_argv(sys.argv[1:])
    parser = argparse.ArgumentParser(description="Scaffold, validate, or promote a local helper")
    sub = parser.add_subparsers(dest="command", required=True)

    p_scaffold = sub.add_parser("scaffold", help="create ${SIPS_HOME:-$HOME/.codex/sips}/scripts/<name>.<ext> + .md spec")
    p_scaffold.add_argument("name", help="helper name")
    p_scaffold.add_argument("--summary", required=True, help="one-line purpose")
    p_scaffold.add_argument("--lang", choices=["py", "sh"], default="py")
    p_scaffold.add_argument("--dry-run", action="store_true", help="show plan without writing")
    p_scaffold.set_defaults(func=cmd_scaffold)

    p_validate = sub.add_parser("validate", help="execute contract cases and write a versioned receipt")
    p_validate.add_argument("name", help="helper name")
    p_validate.add_argument("--script", help="explicit local helper path")
    p_validate.add_argument("--lang", choices=["py", "sh"], default="py")
    p_validate.add_argument("--summary", default="(no summary)",
                            help=argparse.SUPPRESS)  # accept but ignore for cmd_validate parity
    p_validate.set_defaults(func=cmd_validate)

    p_promote = sub.add_parser("promote", help="package a validated content-addressed helper")
    p_promote.add_argument("name", help="helper name")
    p_promote.add_argument("--script", help="explicit local helper path")
    p_promote.add_argument("--lang", choices=["py", "sh"], default="py")
    p_promote.add_argument("--summary", default="(promoted from tool_factory)",
                            help=argparse.SUPPRESS)  # accept but ignore
    p_promote.set_defaults(func=cmd_promote)

    args = parser.parse_args(argv)
    if not hasattr(args, "func"):
        parser.print_help(sys.stderr)
        sys.exit(2)
    try:
        args.func(args)
    except (ValueError, OSError) as exc:
        parser.exit(2, str(exc) + "\n")


if __name__ == "__main__":
    main()
